name: Automated-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Install ps2eth
      run: |
        git clone https://github.com/ps2dev/ps2eth.git
        cd ps2eth && make clean all install
    - name: Compile wLaunchELF
      run: |
        make
    - name: make lang package and elf package
      run: |
       cd Lang
       zip  Lang.zip *.LNG
       cd ..
       HASH=${GITHUB_SHA::7}
       zip "wLaunchELF 4.43a_ISR [$HASH].zip" *.ELF
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: wLaunchELF-${{ steps.slug.outputs.sha8 }}
        path: |
              *.zip
              Lang/Lang.zip
    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "release ${{ steps.slug.outputs.sha8 }}"
        prerelease: false
        title: "Latest automated release"
        files: |
               *.zip
               Lang/Lang.zip
